.lintstagedrc
package.json
playwright.config.js
pnpm-lock.yaml
prettier.config.cjs
src/components/extended-button/__tests__/__snapshots__/extended-button.test.snap.js
src/components/extended-button/__tests__/extended-button.test.js
src/components/test-input/__tests__/__snapshots__/test-input.test.snap.js
src/components/test-input/__tests__/test-input.test.js
src/components/test-input/src/test-input.template.js
src/components/test-input/test-input.js
tasks/check-license.cjs
vite.config.js

Closes #
**New**
**Changed**
**Removed**

chore(tests): set up web-test-runner and example tests

---

package.json
pnpm-lock.yaml
tasks/check-license.cjs

Closes #
https://github.com/carbon-design-system/carbon-for-ai/pull/28
**Changed**
- `globby` version to v14
- Updated to dynamic import of `globby` in license check

chore(globby): upgrade to v14

---

.github/workflows/release.yml
packages/chat/CHANGELOG.md
packages/chat/package.json
packages/extended-button/CHANGELOG.md
packages/extended-button/package.json

Closes #
Edit the `release.yml` file to make sure the checks are working for lerna to publish correctly
**Changed**
- edit `release.yml` file and push out a test rc release with lerna

chore(release): ensure release gh-actions work with dry-run and force publish inputs

---

package.json
packages/chat/components/test-input/test-input.ts
packages/chat/package.json
packages/extended-button/components/extended-button/extended-button.ts
packages/extended-button/package.json
packages/utilities/index.js
packages/utilities/package.json
packages/utilities/src/index.js
packages/utilities/src/settings/index.js
packages/utilities/src/settings/settings.js
pnpm-lock.yaml

Closes #
Create a utilities package that hosts needed files / utils shared amongst the packages. I've added the `settings` file that sets the prefix throughout the components in each package.
**New**
- `@carbon/ai-utilities` package that will house common utils amongst the packages
- Added `settings` file that sets the prefixes to the `@carbon/ai-utilities` package
- Add dependency to the `@carbon/ai-utilities` package in all the component packages' package.json
- build step for the utilities package added to the root `build` script
**Changed**
- set components to get prefix value from the `@carbon/ai-utilities` package instead of hardcoding

chore(utilities): create utilities package

---

.prettierignore
.stylelintignore
README.md
docs/developing.md
package.json

Closes #
Add documentation for developer contributors. 
**New**
- Developing doc
- add `ci-check` command

docs(developing): add documentation for developer contributors

---

docs/developing.md

Closes #
Fix formatting for prettier
**New**
**Changed**
**Removed**

chore(prettier): format developing doc

---

docs/support-for-carbon-v10.md
package.json
packages/chat/package.json
packages/extended-button/package.json
pnpm-lock.yaml

Closes #
Update the package versions to latest `@carbon/styles` and `@carbon/web-components`
**Changed**
- update version in CDN links within the CDN documentation to latest version (v2.1.0)
- upgrade to latest `@carbon/styles` and `@carbon/web-components` package versions

chore(cwc): update to latest cwc version

---

docs/support-for-carbon-v10.md

Closes #
none
**New**
**Changed**
- Added links to the top of method 2 with CDN stackblitz
**Removed**

feat(stackblitz): add examples

---

packages/chat/components/chat/__stories__/chat.stories.js
packages/chat/components/chat/src/chat.scss
packages/chat/components/chat/src/chat.template.ts
packages/chat/components/chat/src/chat.ts
packages/chat/components/message/src/message.scss
packages/chat/components/message/src/message.template.ts
packages/chat/components/message/src/message.ts
packages/chat/services/LlamaPlugin/LlamaPlugin.ts

Closes #
**New**
**Changed**
**Removed**

feat(chat): reworking of error handling, story controls, added video

---

.github/workflows/release-package.yml

Closes #
**New**
**Changed**
**Removed**

chore(release): new release workflow for specific package

---

package.json
packages/chat/package.json
packages/extended-button/package.json
pnpm-lock.yaml

Closes #
Update `@carbon/web-components` to `2.4.0` and `@carbon/styles` to `1.51.0`

chore(dependencies): update carbon dependencies

---

.storybook/preview.js
.storybook/theme.js
README.md
package.json
packages/extended-button/package.json
pnpm-lock.yaml

Closes #
Repo is renamed to `carbon-labs` so changing the storybook title to reflect that. 
Also making the sample `extended-button` component private
**New**
**Changed**
**Removed**

chore(storybook): update storybook title

---

.github/workflows/ci.yml

Closes #
Errors that occur on build or build:dist aren't detected in the `ci-check`, add the build commands to the check.
**New**
**Changed**
**Removed**

chore(actions): add build check to ci-check

---

docs/developing.md
package.json

Closes #
Add new script that combines `ci-check` with the `build` and `build:dist` scripts
**New**
**Changed**
**Removed**

chore(script): add new cmd with ci-check and build

---

.github/CONTRIBUTING.md
.github/ISSUE_TEMPLATE/QUESTION.yaml
docs/developing.md
packages/feedback/package.json

Closes #
Swapping over `carbon-for-ai` to `carbon-labs` in files that were left out.
**New**
**Changed**
**Removed**

chore(rename): swap carbon-for-ai to carbon-labs

---

package.json
packages/chat/package.json
packages/extended-button/package.json
packages/feedback/package.json
yarn.lock

Updates `@carbon/web-components` to `v2.6.0`

chore(dependencies): update @carbon/web-components to 2.6.0

---

packages/chat/CHANGELOG.md
packages/chat/package.json
packages/extended-button/CHANGELOG.md
packages/extended-button/package.json
packages/feedback/CHANGELOG.md
packages/feedback/package.json
packages/network-graph/CHANGELOG.md
packages/network-graph/package.json
packages/utilities/CHANGELOG.md
packages/utilities/package.json
yarn.lock

Closes #
**New**
**Changed**
**Removed**

chore(merge): merge from release/v0.4.0 branch

---

packages/chat/CHANGELOG.md
packages/chat/package.json
packages/feedback/CHANGELOG.md
packages/feedback/package.json
packages/network-graph/CHANGELOG.md
packages/network-graph/package.json
packages/utilities/CHANGELOG.md
packages/utilities/package.json
yarn.lock

Closes #
merging changes from the release/v0.5.0 branch

chore(publish): merge from release/v0.5.0

---

packages/chat/components/codeElement/__stories__/codeElement.stories.js
packages/chat/components/editableTextElement/__stories__/editableTextElement.stories.js

Correct component names so it appears correctly in code and editable text stories

fix(storybook): correct component names

---

packages/chat/CHANGELOG.md
packages/chat/package.json
packages/feedback/CHANGELOG.md
packages/feedback/package.json
packages/network-graph/CHANGELOG.md
packages/network-graph/package.json
packages/utilities/CHANGELOG.md
packages/utilities/package.json
yarn.lock

Closes #
**New**
**Changed**
**Removed**

chore(publish): merge from release/v0.7.0

---

packages/chat/CHANGELOG.md
packages/chat/package.json
packages/feedback/CHANGELOG.md
packages/feedback/package.json
packages/network-graph/CHANGELOG.md
packages/network-graph/package.json
packages/utilities/CHANGELOG.md
packages/utilities/package.json
yarn.lock

Closes #
**New**
**Changed**
**Removed**

chore(publish): merge from release/v0.8.0

---

packages/chat/CHANGELOG.md
packages/chat/package.json
packages/feedback/CHANGELOG.md
packages/feedback/package.json
packages/network-graph/CHANGELOG.md
packages/network-graph/package.json
packages/utilities/CHANGELOG.md
packages/utilities/package.json
yarn.lock

Closes #
**New**
**Changed**
**Removed**

chore(publish): merge from release/v0.9.0

---

packages/chat/CHANGELOG.md
packages/chat/package.json
packages/feedback/CHANGELOG.md
packages/feedback/package.json
packages/network-graph/CHANGELOG.md
packages/network-graph/package.json
packages/tag/CHANGELOG.md
packages/tag/package.json
packages/utilities/CHANGELOG.md
packages/utilities/package.json
yarn.lock

Closes #
**New**
**Changed**
**Removed**

chore(release): merge changelogs from release/v0.11.0

---

packages/chat/CHANGELOG.md
packages/chat/package.json
packages/feedback/CHANGELOG.md
packages/feedback/package.json
packages/network-graph/CHANGELOG.md
packages/network-graph/package.json
packages/prompt-tuning/CHANGELOG.md
packages/prompt-tuning/package.json
packages/tag/CHANGELOG.md
packages/tag/package.json
packages/utilities/CHANGELOG.md
packages/utilities/package.json
yarn.lock

Closes #
**New**
**Changed**
**Removed**

chore(publish): merge changelog and version bumps from release branch

---

packages/chat/CHANGELOG.md
packages/chat/package.json

- @carbon-labs/ai-chat@0.13.0-rc.1
Closes #
**New**
**Changed**
**Removed**

chore(release): publish

---

tools/check-license.cjs

update check-license script to update year on staged files

chore(check-license): staged script wasn't working

---

packages/chat/components/linkListElement/__stories__/link-list.mdx

Closes #
**New**
**Changed**
**Removed**

chore(storybook): add meta component for link list story

---

packages/chat/package.json
yarn.lock

**Changed**
- Update `@ibm/telemetry-js` to latest v1.6.0

chore(telemetry): update to v1.6.0

---

packages/chat/components/carouselElement/src/carouselElement.ts
packages/chat/components/chartElement/src/chartElement.ts
packages/chat/components/codeElement/src/codeElement.ts
packages/chat/components/header/src/header.scss
packages/chat/components/header/src/header.template.ts
packages/chat/components/linkListElement/src/linkListElement.scss
packages/chat/components/message/src/message.scss
packages/chat/components/message/src/message.template.ts
packages/chat/components/tableElement/src/tableElement.scss
packages/chat/components/textElement/__stories__/textElement.stories.js
packages/chat/components/textElement/src/textElement.scss
packages/chat/components/textElement/src/textElement.template.ts

Closes #
**New**
**Changed**
**Removed**

chore(chat): resize, styling, accessibility fixes

---

.github/workflows/create-release-tag-and-pr.yml
.github/workflows/publish-cdn.yml
.github/workflows/release.yml
.github/workflows/storybook-publish-production.yml
.github/workflows/storybook-publish-staging.yml

Closes #
Updates the workflow by automatically triggering the CDN and storybook deployment workflows once the release has been published successfully
**New**
**Changed**
**Removed**

chore(workflows): update workflows

---

README.md
packages/chat/telemetry.yml

This PR updates the endpoint within each package's `telemetry.yml` file with the new stable endpoint for the collector. Also, this updates the wording used in the telemetry notice under each README.
**Changed**
- `telemetry.yml` endpoint to new stable endpoint
- updated wording under telemetry notice in each README
N/A

chore(telemetry): update endpoint and readme

---

.storybook/welcome/Welcome.jsx
.storybook/welcome/welcome.scss
README.md

- add "How to contribute" link in the main storybook welcome page
- fix link widths

feat: add how to contribute link to welcome page

---

README.md

Update README copy
**New**
**Changed**
**Removed**

chore(docs): update labs readme

---

packages/react/src/components/ExampleButton/__stories__/ExampleButton.mdx
packages/react/tasks/generate/templates/__stories__/DISPLAY_NAME.mdx

Add the maintainer's block to the storybook docs

chore: add maintainer block to docs

---

.github/workflows/release-minor.yml

Adding an additional configuration to bypass branch protection rules for Lerna actions

fix(ghactions): add token fix for lerna

---

.github/workflows/ci.yml
.github/workflows/pr.yml
.github/workflows/release-minor.yml

This add merge queue functionality.
Also adds a workflow to check the PR subject formatting.

chore(ghactions): add merge queue

---

.github/workflows/dco.yml
.github/workflows/release-minor.yml

This adds the dco workflow to the merge queue checks.

chore(ghactions): add dco to merge queue check  @jeffchew

---

examples/react/UIShell/src/App.tsx
packages/react/src/components/UIShell/__stories__/UIShell.mdx
packages/react/src/components/UIShell/__stories__/UIShell.stories.js
packages/react/src/components/UIShell/components/SideNav.tsx
packages/react/src/components/UIShell/components/styles/_side-nav.scss

Related [#18492](https://github.com/carbon-design-system/carbon/issues/18492)
Followup after design feedback to https://github.com/carbon-design-system/carbon-labs/pull/398
**New**
- hideOverlay prop to SideNav

feat(UIShell): add hideoverlay prop to sidenav

---

packages/react/src/components/UIShell/__stories__/UIShell.stories.js
packages/react/src/components/UIShell/components/SideNav.tsx
packages/react/src/components/UIShell/components/SideNavToggle.tsx
packages/react/src/components/UIShell/components/styles/_side-nav.scss

Ref https://github.com/carbon-design-system/carbon/issues/18446
This PR implements the new SideNav panel variant

feat(SideNav): implement panel variant

---

packages/react/src/components/UIShell/__stories__/UIShell.stories.js
packages/react/src/components/UIShell/components/styles/_side-nav.scss

fix(UIShell): update zindex and update main uishell story

---

examples/react/UIShell/src/App.tsx
packages/react/src/components/UIShell/index.ts

This PR updates the React UIShell sandbox example to match the default story
**Changed**
- update UIShell exports
- update UIShell sandbox example

docs(UIShell): update example

---

examples/react/UIShell/src/App.tsx
packages/react/src/components/UIShell/components/SideNavMenu.tsx
packages/react/src/components/UIShell/components/SideNavMenuItem.tsx

**Changed**
- changed component imports from `/lib/ to `/es/`

fix(SideNav): fixed imports

---

examples/react/UIShell/src/index.scss
packages/react/src/components/UIShell/__stories__/UIShell.mdx

- Updates to overview.mdx with latest component updates
- add plex to example

docs(UIShell): update overview page and add plex to example

---

packages/react/src/components/UIShell/__stories__/AppIcons.js
packages/react/src/components/UIShell/__stories__/UIShell.stories.js

- new AppIcons file for demo svgs
- update default story for UIShell in storybook with app icons and icons

docs(UIShell): update default story with icons

---

packages/react/src/components/UIShell/components/styles/_header.scss

Closes #424
**Changed**
- update focus to 2px for hamburger menu

fix(uishell): update focus state for hamburger to 2px

---

examples/react/UIShell/src/App.tsx
packages/react/src/components/UIShell/README.md
packages/react/src/components/UIShell/__stories__/UIShell.mdx
packages/react/src/components/UIShell/__stories__/UIShell.stories.js
packages/react/src/components/UIShell/components/SideNav.tsx
packages/react/src/components/UIShell/components/SideNavLink.tsx
packages/react/src/components/UIShell/components/SideNavLinkPopover.tsx
packages/react/src/components/UIShell/components/styles/_side-nav.scss
packages/react/src/components/UIShell/index.ts

Closes #418 
This PR introduces the SideNavLinkPopover component
**New**
- move SideNavLink into local repo
- SideNavLinkPopover
**Changed**
- side nav overflow styles
confirm the expected behavior and appearance of the side nav links

feat(SideNavLinkPopover): create component 

---

packages/react/src/components/UIShell/__stories__/UIShell.stories.js
packages/react/src/components/UIShell/components/HeaderContainer.tsx
packages/react/src/components/UIShell/index.ts

This PR adds a HeaderContainer component with bugfixes for separating left header menu and right header panel/switcher expansion state
it also introduces `onClickSwitcherExpand` to match the existing `onClickSideNavExpand` API

feat(UIShell): add HeaderContainer

---

.github/CODEOWNERS

Contributes to carbon-design-system/ibm-products#6978
Update CODEOWNERS to IBM Products reviewer team.
**Changed**
- CODEOWNERS

chore: update default reviewer team

---

.github/CODEOWNERS

Closes #524 
Set per package CODEOWNERS.
> [!NOTE]
> Will add ~ThemeSettings~ ✅, Processing, and SplitPanel as those PRs are merged. 
**Changed**
- add codeowners for contributed React packages
Valid CODEOWNERS file

chore: add package-specific review teams

---

packages/react/src/components/UIShell/README.md
packages/react/src/components/UIShell/__stories__/UIShell.mdx
packages/react/src/components/UIShell/__stories__/UIShell.stories.js
packages/react/src/components/UIShell/components/HeaderAction.tsx
packages/react/src/components/UIShell/components/HeaderPopover.tsx
packages/react/src/components/UIShell/components/styles/_header.scss
packages/react/src/components/UIShell/index.ts

Closes #462
This PR adds the HeaderPopover component, a popover component used in the header

feat(UIShell): add HeaderPopover

---

examples/react/UIShell/src/App.tsx
packages/react/src/components/UIShell/README.md
packages/react/src/components/UIShell/__stories__/UIShell.mdx
packages/react/src/components/UIShell/__stories__/UIShell.stories.js

This PR updates storybook and stackblitz with the latest components and design
**Changed**
- Updated and reorganized overview docs
- Update default and header story based on designs from Olivia
- Removed HeaderMenu/HeaderMenuItem from example
- Re-ordered and updated icons
- Update stackblitz example with latest
**Removed**
- HeaderPanel story & docs (no updates in labs, so not needed, leaving the component just in case anyone is importing it)

docs(UIShell): update storybook and stackblitz

---

packages/react/src/components/AnimatedHeader/__stories__/AnimatedHeader.mdx
packages/react/src/components/AnimatedHeader/components/AnimatedHeader/AnimatedHeader.tsx
packages/react/src/components/AnimatedHeader/components/Tiles/BaseTile/BaseTile.tsx
packages/react/src/components/AnimatedHeader/components/Tiles/GlassTile/GlassTile.tsx

Allow user to pass a method that will be called while tiles are clicked.
**New**
- tileClickHandler prop added

feat: add-tile-click-prop

---

examples/react/UIShell/package.json
examples/react/UIShell/src/App.tsx
packages/react/package.json
packages/react/src/components/AnimatedHeader/__tests__/__snapshots__/AnimatedHeader-test.tsx.snap
packages/react/src/components/ThemeSettings/__tests__/__snapshots__/ThemeSettings-test.js.snap
packages/react/src/components/ThemeSettings/components/ThemeSwitcher.tsx
packages/react/src/components/UIShell/__stories__/Profile.mdx
packages/react/src/components/UIShell/__stories__/Profile.stories.js
packages/react/src/components/UIShell/__stories__/UIShell.stories.js
packages/react/src/components/UIShell/components/HeaderContainer.tsx
packages/react/src/components/UIShell/components/Profile.tsx
packages/react/src/components/UIShell/components/styles/_header.scss
packages/react/src/components/UIShell/components/styles/_profile.scss
yarn.lock

Closes #666 
Add theme switching to profile
**Changed**
-  import theme settings package
- update react/styles packages for lowContrast option
- changed the ThemeSwitcher to accept `...rest` for size and lowcontrast
- add new story and update demo and example
- cleanup profile
- added overlfow if profile gets too long
check profile stories

feat(profile): add theme-switcher

---

packages/react/src/components/UIShell/components/SideNav.tsx

Closes #722 
prevent close on back button
**Changed**
- added an additional check to prevent back button closing side nav on click
check mobile and try clicking on back button

fix(uishell): back button prevent close

---

examples/react/FirstTimeOrientation/package.json
examples/react/FirstTimeOrientation/src/App.tsx
packages/react/src/components/FirstTimeOrientation/__stories__/FirstTimeOrientation.stories.jsx
packages/react/src/components/FirstTimeOrientation/package.json
yarn.lock

Closes # [7554](https://github.com/carbon-design-system/ibm-products/issues/7554)
Updated `isOpen` prop to `open` as per latest
Updated `package.json` and `yarn.lock` with latest ibm/products package
storybook

fix(firstTimeOrientation): pattern not opening after upgrade

---

packages/react/src/components/UIShell/__stories__/SideNav.stories.js
packages/react/src/components/UIShell/__stories__/UIShell.stories.js

[Request from Adam in slack.](https://ibm-studios.slack.com/archives/C080CBHPHNE/p1755877720911819)
Updates all links for UI Shell stories to be # so you aren't accidentally taken to another site

docs(uishell): remove links from storybook

---

examples/react/UIShell/src/components/HeaderExample.tsx
examples/react/UIShell/src/components/HeaderGlobalBarExample.tsx
examples/react/UIShell/src/config/routes.tsx
examples/react/UIShell/src/index.scss
examples/react/UIShell/src/main.tsx

Closes #792
- Update theme to be white/g10 & g90/g100 with theme switching
- Add Profile components
- Update product nav to use navType={SIDE_NAV_TYPE.RAIL_PANEL}  
Check that Stackblitz loads and isn't missing anything. 
https://stackblitz.com/github/alisonjoseph/carbon-labs/tree/update-uishell-stackblitz/examples/react/UIShell?file=package.json

docs(UIShell): update Stackblitz

---

packages/web-components/src/components/global-header/components/global-header/src/components/CommonHeader/__stories__/CommonHeader.stories.ts

fix icons in storybook entry, and make names more generic

fix(wc-global-header): update icons in storybook entry
