- .github/workflows/release-canary.yml
Closes #
Add github actions workflow that publishes the canary versions of the packages on push to `main`
**New**
**Changed**
**Removed**
> chore(publish): canary publish workflow

- docs/support-for-carbon-v10.md
Part of https://github.com/carbon-design-system/carbon-for-ai/issues/25
**New**
- Add documentation on support for Carbon v10
- Review the docs, it's mostly a copy paste of my comments so far on https://github.com/carbon-design-system/carbon-for-ai/issues/25
- This does not include information on the CDN approach as I'm not familiar enough with it to explain or outline pros/cons, etc. but I stubbed it out in the document.
> docs: provide guidance on support for carbon v10

- .github/workflows/publish-canary-cdn.yml
- .github/workflows/publish-cdn.yml
Closes #
Need to build packages before the `pnpm:dist` commands
**New**
**Changed**
**Removed**
> chore(cdn-workflow): add build step before dist step in cdn workflow

- .stylelintrc
Closes #
The stylelint rule of max nesting set to 0 is a little too strict, opening up to have up to 2 levels of nesting
**New**
**Changed**
**Removed**
> chore(stylelint): adjust stylelint rule to allow nesting

- packages/chat/react/feedback.ts
- packages/chat/react/test-input.ts
- packages/extended-button/react/extended-button.ts
- packages/utilities/src/index.js
- packages/utilities/src/settings/index.js
Closes N/A
This PR adds React wrappers for existing components. This utilizes the `@lit/react` package - currently we need to manually create these React wrapper files, but looking into automating the file creation in the future.
**New**
- React wrappers for existing components
**Changed**
- be specific with the reference paths for settings utilities package
> feat(react): add react wrapper components

- README.md
- packages/chat/package.json
- packages/chat/telemetry.yml
- pnpm-lock.yaml
Adds config required for telemetry collection to `@carbon-labs/ai-chat` package.
**New**
- Added Telemetry disclosure to top-level README
- Added @ibm/telemetry-js dependency to `@carbon-labs/ai-chat`
- Added postinstall script to invoke telemetry collection
- Added telemetry.yml config file configured with npm scope.
- Included `telemetry.yml` in `@carbon-labs/ai-chat` package.json files
**Changed**
- N/A
**Removed**
- N/A
N/A
> chore: onboard @carbon-labs/ai-chat to IBM Telemetry 🚀

- gulp-tasks/build/modules/css.js
- gulp-tasks/build/modules/scripts.js
- gulp-tasks/build/modules/types.js
- package.json
- packages/chat/package.json
- packages/extended-button/package.json
- pnpm-lock.yaml
Closes #
This PR adds a build script to each package so that each package can run it's own build. Each package can build and run regardless of the other packages. Setting this up so that we can have publish workflows to publish only one specific package at a time.
**Changed**
- build script for each package - each build script passes in the component name as an argument in the command and runs the gulp pipeline on just that specific package
**Removed**
> chore(build): separate build commands to each package

- package.json
- pnpm-lock.yaml
Closes #
Bumps up `sass` and `@carbon/icons` package versions
**Changed**
- bump `@carbon/icons` to v11.36.0
- bump `sass` to `~1.71.0`
> chore(dependency): update dependencies

- .github/workflows/storybook-publish-production.yml
- .github/workflows/storybook-publish-staging.yml
Closes #
With the renaming of `Carbon for AI` to `Carbon Labs` we are renaming the github action secrets to be consistent
**Changed**
- Change prefix of github action secrets to `CLABS` for the storybook env workflows
> feat(actions): rename github action secrets to labs

- globals/internal/storybook-cdn.ts
- packages/feedback/__stories__/feedback.mdx
- packages/feedback/__stories__/feedback.stories.js
- packages/feedback/examples/feedback/.gitignore
- packages/feedback/examples/feedback/cdn.html
- packages/feedback/examples/feedback/index.html
- packages/feedback/examples/feedback/package.json
- packages/feedback/examples/feedback/src/index.js
- packages/feedback/examples/feedback/src/styles.scss
Contributes to #98 
Adds `feedback.mdx` file for documentation which includes the link to the stackblitz example. 
Adds example folder for `feedback` containing stackblitz files
**New**
- `feedback.mdx` with link to Stackblitz example which is also added in this PR
- `storybook-cdn` file added to global to generate the cdn links
> chore(feedback): add stackblitz example for feedback component

- .storybook/preview.js
- package.json
- yarn.lock
Closes #
Removing `@carbon/web-components` package from root as we're only using it for the `skip-to-content` component in our storybook.
> chore(storybook): remove cwc from root package.json

- .github/CODEOWNERS
This adds codeowners so that specific components can be owned by maintainer library teams
**New**
- CODEOWNERS file
> chore(codeowners): adding CODEOWNERS

- packages/web-components/src/components/example-button/CHANGELOG.md
- packages/web-components/src/components/example-button/__stories__/example-button.stories.js
- packages/web-components/src/components/example-button/__tests__/__snapshots__/extended-button.test.snap.js
- packages/web-components/src/components/example-button/__tests__/example-button.test.ts
- packages/web-components/src/components/example-button/components/example-button/example-button.ts
- packages/web-components/src/components/example-button/components/example-button/src/example-button.scss
- packages/web-components/src/components/example-button/components/example-button/src/example-button.template.ts
- packages/web-components/src/components/example-button/index.ts
- packages/web-components/src/components/example-button/package.json
- packages/web-components/src/components/example-button/react/example-button.ts
- yarn.lock
Closes #264 
Adds back boilerplate component to the web-components package, `example-button`
**New**
- adds component package for boilerplate component (`example-button`)
- commented out the commands for CDN generation as we don't need it to be uploaded
- storybook 
ci-checks passing
> chore: add boilerplate web component

- package.json
- packages/react/package.json
- packages/react/tasks/generate/index.js
- packages/web-components/tasks/generate/index.js
- yarn.lock
Moves the shared dependencies used for the `generate` script in both web-components and React packages to the root package.json
> chore: move shared dependencies to root

- README.md
- docs/developing.md
Closes #347 
Edit the developer guide to include the use of the `generate` script.
**Changed**
- Update documentation to use the `generate` script instead.
- Update documentation in root README
> docs: edit developer docs to include script

- docs/developing.md
- packages/react/tasks/generate/templates/__tests__/DISPLAY_NAME.test.js
- packages/react/tasks/generate/templates/example/package-edit.json
This PR removes majority of the test cases in the generated component template, leaving behind just one test that will generate a snapshot for basic component render.
> chore: change react template test to one snapshot test

- examples/react/UIShell/src/App.tsx
- packages/react/src/components/UIShell/__stories__/UIShell.mdx
- packages/react/src/components/UIShell/__stories__/UIShell.stories.js
- packages/react/src/components/UIShell/__tests__/SideNav-test.js
- packages/react/src/components/UIShell/__tests__/__snapshots__/SideNav-test.js.snap
- packages/react/src/components/UIShell/components/SideNav.tsx
- packages/react/src/components/UIShell/components/styles/_side-nav.scss
- packages/react/src/components/UIShell/components/ui-shell.scss
Closes https://github.com/carbon-design-system/carbon/issues/18492
- update example code (what shows up in stackblitz once published)
- update overview page in storybook
- add default shell story with theme component and demo content
- isolate sidenav story
- add new `isCollapsible` prop to `SideNav`
- copy over tests from @carbon/react for `SideNav`
- Commented out 2 failing tests - will look at separately, shouldn't block this
- add basic test for new prop
Test hamburger functionality in Default story th
@oliviaflory do we want the overlay, currently by default it does pop up but I can make it configurable if needed.
> feat(SideNav): add header menu button functionality at desktop

- packages/react/src/components/UIShell/README.md
- packages/react/src/components/UIShell/package.json
- packages/react/src/components/UIShell/telemetry.yml
- yarn.lock
Closes #397 
Adds telemetry to the UI shell package so we can track and monitor adoption of the package.
**New**
- `telemetry.yml` file, which is generated by the
- `telemetry:config` script, to run whenever we add React components that have net-new prop or prop values for the package
- `README.md` to put the telemetry notice
- `@ibm/telemetry-js` dependency
**Changed**
- N/A
**Removed**
- N/A
I generated and saved the telemetry project ID. Not really sure how to test this PR; we've never really tested the instrumented PRs. One thing to note, the `telemetry:config` script generated an empty array for `allowedAttributeStringValues` which caused YAML validation errors. Because of this, I manually added `true` and `false` as allowed prop values for now.
> chore(UIShell): add telemetry to UI shell package

- examples/react/UIShell/src/App.tsx
- packages/react/src/components/UIShell/__stories__/UIShell.mdx
- packages/react/src/components/UIShell/__stories__/UIShell.stories.js
- packages/react/src/components/UIShell/__tests__/HeaderPanel-test.js
- packages/react/src/components/UIShell/components/HeaderPanel.tsx
- packages/react/src/components/UIShell/components/styles/_side-nav.scss
- packages/react/src/components/UIShell/index.ts
Closes #409
Bring over HeaderPanel component as is from @carbon/react to labs to prepare for future right panel enhancements design is working on [#18449](https://github.com/carbon-design-system/carbon/issues/18449)
**New**
- add `HeaderPanel` React component inside of UIShell package
Check that the panel renders https://deploy-preview-407--carbon-labs-react.netlify.app/?path=/story/components-uishell--header-panel-story
> feat(UIShell): add HeaderPanel to UIShell React package

- packages/react/src/components/UIShell/components/SideNav.tsx
- packages/react/src/components/UIShell/components/SideNavToggle.tsx
Closes #425
This PR fixes a regression that caused the SideNavToggle tab index value to reset
**Changed**
- side nav menu tab index reset logic
Confirm that the SideNavToggle is accessible by keyboard once again
> fix(SideNav): prevent SideNavToggle tabindex reset

- examples/react/UIShell/src/App.tsx
- packages/react/.storybook/styles.scss
- packages/react/src/components/UIShell/__stories__/UIShell.mdx
- packages/react/src/components/UIShell/__stories__/UIShell.stories.js
- packages/react/src/components/UIShell/components/styles/_content.scss
- packages/react/src/components/UIShell/components/styles/_side-nav.scss
- packages/react/src/components/UIShell/components/ui-shell.scss
Closes #416
**New**
- add missing styles to storybook to enable theme switcher
- add content styles when combined with sidenav panel
**Changed**
- update default story
- update example 
Check that SideNav panel now acts as a grid influencer in default story and panel story.
> feat(UIShell): SideNav panel as grid influencer

- packages/react/src/components/ExampleButton/components/example-button.scss
This import of Carbon button styles in the example component isn't needed and is overriding UIShell styles due to the order styles are being imported into storybook. 
**Removed**
- import for button styles in example component
> fix: remove button style import

- packages/react/src/components/UIShell/components/SideNav.tsx
Closes #483
**Changed**
- makes it so the first `SideNavMenuItem` gains `tabIndex=0` only when the panel is expanded, or it's a panel `navType`
Tabbed into it
> fix(SideNav): handle unexpanded tabindex

- .github/workflows/ci.yml
Closes #
Running into build errors from the Web Component side - downgrading to Node v18 seems to resolve the issue. Temporary fix until we switch over to use Rollup for builds
**Changed**
- downgrade to Node v18 for the build step in the `ci` checks
Check that the build step for the ci-check passes in this PR
> fix(ci): downgrade node to 18 for ci build step

- .github/workflows/ci.yml
- .github/workflows/create-release-tag-and-pr.yml
- .github/workflows/publish-canary-cdn.yml
- .github/workflows/publish-cdn.yml
- .github/workflows/release-canary.yml
- .github/workflows/release-minor.yml
- .github/workflows/release.yml
- .github/workflows/storybook-publish.yml
Closes #
Downgrading the Node version in the `build` step of the ci-checks seems to resolve the build errors we're seeing in Web Component component builds. This PR downgrades the Node version to 18 for the rest of the workflows.
**Changed**
- downgrade to Node v18 for all workflows
Make sure the ci-checks pass
> fix: downgrade node to 18 in workflows

- packages/react/src/components/UIShell/components/SideNav.tsx
- packages/react/src/components/UIShell/components/SideNavToggle.tsx
- packages/react/src/components/UIShell/components/styles/_side-nav.scss
Closes #496 
This PR ensures that the toggle button when the side nav panel is collapsed doesn't disappear when the screen height gets smaller.
This is mostly for a visual fix for mouse interaction -- using the keyboard to tab still has a weird behavior. The whole reason this is happening is because of the `overflow` css property that is being applied to the side nav contents. If we remove the values that are currently being applied when the menu is collapsed, **the tooltip/flyout menu will not appear**, as they are considered "overflow" and thus hidden away. To fix this behavior, we would need to refactor most of the menu and also the aforementioned components. For now, this visual fix is a basic compromise to be done.
**New**
- wrapper div for the toggle button only to ensure black …
> fix(SideNavToggle): show on screen height resize

- packages/react/src/components/WhatsNew/components/whats-new.scss
Closes #510 
This PR fixes the issue where the styles were duplicated throughout all components, meaning that new 'state' styles were overridden by their default styles. This duplication was caused in the latest `WhatsNew` component, where it includes `use @carbon/react;` in the component styles. This makes Storybook grab all the styles from the package and reimport them, essentially.
**Removed**
- nonessential `@carbon/react` style import
Since this would only change prod Storybook due to the way styles are bundled with Webpack, we can't test if this fixes the issue. 
However, since this change concerns the new What's New component, testing this PR would just be to ensure there are no unexpected changes after doing this change.
> fix(UIShell): resolve storybook z-index issue

- packages/react/src/components/UIShell/components/SideNavMenu.tsx
Closes #448 
This PR adds a click hook where adopters can add a function that will run when SideNavMenu has been toggled.
**New**
- adds `onMenuToggle` prop to `SideNavMenu` that takes a function to run when menu is toggled
You can pull this PR locally, and add `onMenuToggle={() => console.log('test')}` to any of the SideNavMenus and see the output when interacting with it on the console.
> feat(UIShell): add onClick hook to SideNavMenu

- README.md
Noticed the readme was missing some of the recently added packages.
> docs: add all new components to readme

- packages/react/src/components/Processing/__tests__/__snapshots__/Processing.test.js.snap
- packages/react/src/components/Processing/components/Processing.tsx
- packages/react/src/components/Processing/components/processing.scss
#490 was merged in before the issue here could be fixed 
**New**
- N/A
**Changed**
- Removed unused button import from `processing.scss`
- Fixed center display of processing element in storybook for only processing component
**Removed**
- N/A
- Local host / preview
> fix(processing): remove button import + fix storybook style

- examples/react/AnimatedHeader/src/App.tsx
- examples/react/AnimatedHeader/src/data/index.jsx
- packages/react/src/components/AnimatedHeader/__stories__/AnimatedHeader.mdx
- packages/react/src/components/AnimatedHeader/__stories__/AnimatedHeader.stories.tsx
- packages/react/src/components/AnimatedHeader/__stories__/data/index.jsx
- packages/react/src/components/AnimatedHeader/__tests__/AnimatedHeader-test.tsx
- packages/react/src/components/AnimatedHeader/__tests__/__snapshots__/AnimatedHeader-test.tsx.snap
- packages/react/src/components/AnimatedHeader/components/AnimatedHeader/AnimatedHeader.tsx
- packages/react/src/components/AnimatedHeader/data/index.jsx
Allows the end user to control custom `itemToString` function
**New**
- N/A
**Changed**
- Two new props:
- handleHeaderItemsToString: (item) => string;
- handleWorkspaceItemsToString: (item) => string;
**Removed**
- Remove `animationContainer` from useEffect dependency array
localhost / Preview
> feat(animated-header): add custom itemToString func for Dropdowns

- packages/react/src/components/AnimatedHeader/components/AnimatedHeader/AnimatedHeader.tsx
Remove load or continuous animation behind content. Only allow 5 second load animation
**New**
- N/A
**Changed**
- Remove "loop" animation and only allow "load" animation
**Removed**
- N/A
Localhost / Preview
> feat(animated-header): remove loop animation from header

- packages/react/.storybook/preview.js
Closes #520 
This PR removes the redundant (and malfunctioning) background theme switcher button from Storybook. The paintbrush button is the one that actually does what it's supposed to do.
**Removed**
- removed Storybook background toolbar addon
Button should be gone
> fix(storybook): remove background button

- packages/react/src/components/UIShell/components/styles/_header.scss
Closes #551
This PR removes the box shadow on header global actions so that the focus state is no longer doubled
**Removed**
- header global action box shadow
confirm the component focus state looks correct
> fix(UIShell): remove box-shadow on header action focus

- examples/react/AnimatedHeader/src/main.tsx
- packages/react/src/components/AnimatedHeader/__tests__/__snapshots__/AnimatedHeader-test.tsx.snap
- packages/react/src/components/AnimatedHeader/components/AnimatedHeader/AnimatedHeader.tsx
`<React.StrictMode>` creates issues when rendering Lottie animations (loads content twice). Removed from the example app. Removed tooltip around description. 
**New**
- N/A
**Changed**
- Removed StrictMode from stackblitz example since it created duplicate rendering issue with Lottie
- Removed tooltip around description
**Removed**
- N/A
Localhost / Preview
> feat(animated-header): remove strictmode from example app + tooltip

- packages/react/tasks/generate/templates/README.md
- packages/react/tasks/generate/templates/package-edit.json
- packages/web-components/tasks/generate/templates/README.md
- packages/web-components/tasks/generate/templates/package-edit.json
Closes #489
Update default templates from generate script within `@carbon/labs`
**New**
- Updated `package-edit.json` in both `React` and `Web components` to include `author` option.
- Added `README.md` with basic content in `React` and `Web components` templates.
Run `yarn generate` from `packages/react` or `packages/web-components`
> chore(generate script): update React and WC generate 

- packages/web-components/src/components/empty-state/package.json
Fix mismatched version numbers preventing release.
In the follow up PR to empty state WC, the version number in the empty state `package.json` was downgraded to `0.0.1` — likely missed during a conflict since these get bumped in each release.
**Changed**
- bump empty state package.json back to 0.1.0
> chore: bump empty state version

- packages/react/src/components/AnimatedHeader/components/AnimatedHeader/animated-header.scss
Add backup support for when autoprefixer is not in use
**New**
- N/A
**Changed**
- Add `block-size: -webkit-fill-available;  inline-size: -webkit-fill-available;` as backup
**Removed**
- N/A
Local host
> fix(animated-header): add backup for autoprefixer

- tools/check-license.cjs
Closes #
Allows excess args for commander so precommits will run as expected.
**Changed**
- `tools/check-license.cjs`
> fix: allow excess args for commander

- .github/CODEOWNERS
- README.md
- packages/react/src/components/SplitPanel/__stories__/SplitPanel.mdx
Add missing details from split panel docs
**New**
- Add split panel to CODEOWNERS
- Add split panel in README
> chore: add split panel codeowners

- packages/react/src/components/AnimatedHeader/__stories__/AnimatedHeader.mdx
- packages/react/src/components/AnimatedHeader/__stories__/AnimatedHeader.stories.tsx
- packages/react/src/components/AnimatedHeader/components/AnimatedHeader/AnimatedHeader.tsx
Allow for specifying custom labels for expand/collapse button. Needed since we don't support internationalisation.
**New**
- expandButtonLabel, collapseButtonLabel props
> chore(animated-header): Expose expand/collapse button label

- examples/react/UIShell/src/App.tsx
- packages/react/src/components/UIShell/package.json
Updates UIShell exports and ensures they work in the following scenarios.
JS from
`from '@carbon-labs/react-ui-shell/es/index.js';`
`from '@carbon-labs/react-ui-shell/es';
`from '@carbon-labs/react-ui-shell';`
SCSS 
`@use '@carbon-labs/react-ui-shell/scss/ui-shell';`
Types
`"type": "./es/index.d.ts"`
It looks to me as though a single types file could be used in root or a dist folder.
**Changed**
- packages/react/src/components/UIShell/package.json
- examples/react/UIShell/src/App.tsx
Copied UIShell to a separate folder and tried installing and running from local path.
NOTE: Once the correct pattern is verified for "exports" it should be replicated in the other projects.
> fix: exports in ui shell

- yarn.lock
Reverts carbon-design-system/carbon-labs#573
Looks like web components builds started failing after this update, reverting.
> Revert "fix(deps): update dependency vega to v5.32.0 [security]"

- examples/react/AnimatedHeader/src/App.tsx
- examples/react/AnimatedHeader/src/data/index.tsx
- examples/react/ExampleButton/src/App.tsx
- examples/react/Processing/src/App.tsx
- examples/react/TextHighlighter/src/App.tsx
- examples/react/WhatsNew/src/App.tsx
- packages/react/src/components/AnimatedHeader/package.json
- packages/react/src/components/ExampleButton/package.json
- packages/react/src/components/MDXComponents/package.json
- packages/react/src/components/Processing/package.json
- packages/react/src/components/SplitPanel/package.json
- packages/react/src/components/TextHighlighter/package.json
- packages/react/src/components/ThemeSettings/package.json
- packages/react/src/components/UIShell/package.json
- packages/react/src/components/WhatsNew/package.json
- packages/react/tasks/generate/templates/example/src/App.tsx
- packages/react/tasks/generate/templates/package-edit.json
Related to #603 
Given the verified example of fixing the UI Shell exports and example application, this PR update the remaining react package exports and example imports.
Slight change to sub folder exports to match https://nodejs.org/api/packages.html#subpath-exports
**Changed**
- React package.json files to match UiShell
- Example imports to remove es/index.js
- Updated generate script file.
Was verified locally by checking/updating examples.
To be verified by opening stackblitz examples after publish.
> fix: update exports to match UI shell

- packages/react/src/components/Processing/components/processing.scss
Set default theme for processing to g10
**New**
- N/A
**Changed**
- Add root theme set to g10
**Removed**
- N/A
Preview
> feat(processing): set default theme to g10

- packages/react/src/components/Processing/components/processing.scss
Reverts carbon-design-system/carbon-labs#535
This change is causing the labs storybook to load in g10 theme for all stories not just this one, will need to look into a different way of handling this for this specific component.
> Revert "feat(processing): set default theme to g10"

- examples/react/UIShell/src/App.tsx
- packages/react/src/components/UIShell/__stories__/UIShell.stories.js
- packages/react/src/components/UIShell/components/SideNav.tsx
- packages/react/src/components/UIShell/components/styles/_side-nav.scss
Related #618
this PR adds a media query to hide the side navigation rail on smaller screens
**Changed**
- sidenav rail styles
confirm that the local sidenav rail is not visible at smaller screen sizes
> fix: add breakpoint utility for responsive side-nav rail

- packages/react/src/components/UIShell/components/SideNav.tsx
- packages/react/src/components/UIShell/components/SideNavItems.tsx
- packages/react/src/components/UIShell/components/SideNavMenu.tsx
Ref #649 
>  Tabbing in Firefox. It's a bit unclear to me where the focus is going (within the panels somewhere?) when I hit the tab key on Firefox. Two examples in the video, and also attaching a screen shot of the odd focus indicator that seems like it's between panels?
^there shouldn't be any weird tabbing anymore in any browser
**Changed**
- edited so if it's a primary menu it renders one section of code or the other and not both 
- set tabIndex = -1 if it's a primary menu
- ignores setting a link in a primary sidenavmenu to tabindex = -1 
tab through the sidenav and make sure in firefox that you aren't seeing any random blue lines
> fix(ui-shell): tabbing fixes

- examples/react/UIShell/src/App.tsx
- packages/react/src/components/UIShell/README.md
- packages/react/src/components/UIShell/__stories__/UIShell.mdx
- packages/react/src/components/UIShell/__stories__/UIShell.stories.js
- packages/react/src/components/UIShell/components/SideNav.tsx
- packages/react/src/components/UIShell/components/SideNavMenu.tsx
- packages/react/src/components/UIShell/components/SideNavSlot.tsx
- packages/react/src/components/UIShell/components/styles/_content.scss
- packages/react/src/components/UIShell/components/styles/_side-nav.scss
- packages/react/src/components/UIShell/index.ts
Closes #613 
Closes #618
New `SideNavSlot` component to allow rendering of custom components within the navigation.
Added border to is Rail variant of SideNav
**New**
- `SideNavSlot` component
- Added example with `Dropdown` (tenent switcher)
- Add Layer component internally to SideNavMenu 
- Add border to isRail variant of SideNav
- Add decorate `Menu` icon to the local nav rail. 
**Changed**
- small fix for content margin when rail is hidden
**Removed**
- SideNav panel story
- Panel docs from overview page
Check `Default, `Side Nav` and `Side Nav Rail` stories
> feat(uishell): add new SideNavSlot component and rail updates

- packages/react/src/components/UIShell/components/SideNav.tsx
- packages/react/src/components/UIShell/components/SideNavMenu.tsx
- packages/react/src/components/UIShell/components/styles/_side-nav.scss
Closes #649 
if there is an active link then focus should go to that item first on load
**Changed**
- update focus on first item if there is an active link
- add an overflow to the seconary menu
- make sure escape key is handled
- commented out the `lastExpandedState` seemed to be causing errors and not doing much from what I can tell
check on load tabbing
> fix(sidenav): focus on active

- packages/react/src/components/Resizer/package.json
Fixing up `Resizer` so that we can prep for bringing it into `SidePanel` from labs.
**Changed**
- `packages/react/src/components/Resizer/package.json`
Built `Resizer` package and validated it contains both `es` and `lib` directories.
> fix(Resizer): update entry points for package

- packages/react/src/components/AnimatedHeader/__tests__/__snapshots__/AnimatedHeader-test.tsx.snap
- packages/react/src/components/ThemeSettings/__tests__/__snapshots__/ThemeSettings-test.js.snap
- packages/react/src/components/UIShell/components/styles/_profile.scss
Fix for odd style bug that showed up after we imported ibm-products scss
**Changed**
- import only UserAvatar styles from ibm-products
Check Demo story
> fix(uishell): update style import for ibm-products

- packages/react/src/components/UIShell/components/SideNavMenu.tsx
Closes #677
before the SideNav default would automatically load all the menu's as expanded. This issue was happening because for `primary`  menu's we always want one open which is not applicable for the default
now the default should all show closed:
**Changed**
- cleaned up useEffect if statement setting `setIsExpanded`
> fix(SideNavMenu): expanding issue if not primary

- packages/react/src/components/UIShell/components/styles/_content.scss
Closes #704
- Add additional scss selector to account for when the nav is nested within a Layer component
Check Demo story at mobile breakpoint, there shouldn't be any extra left margin anymore
> fix(uishell): hide rail spacing at small screens when inside layer

- packages/react/src/components/UIShell/components/styles/_profile.scss
Closes #721 
only show scroll bars when the profile needs to scroll
https://github.com/user-attachments/assets/b28e2838-dfcd-4045-841d-123292adc641
this shows the profile menu only showing scroll bars when necessary and the scroll bars don't push the profile menu over but instead go inside the profile container. 
**Changed**
- overflow-y should just be auto not scroll always
open the profile menu and test the scroll bars by shrinking the height of the browser. Turn scroll bars to always on in system settings
> fix(uishell): profile overflow scroll

- .github/workflows/storybook-publish.yml
Has been failing for past two weeks, since storybook 9 upgrade https://github.com/carbon-design-system/carbon-labs/actions/workflows/storybook-publish.yml
> chore: update storybook publish workflow node version

- packages/web-components/src/components/style-picker/__stories__/_placeholders.ts
- packages/web-components/src/components/style-picker/__stories__/style-picker.disclosed.stories.js
- packages/web-components/src/components/style-picker/__stories__/style-picker.flat.stories.js
- packages/web-components/src/components/style-picker/__stories__/style-picker.single.stories.js
- packages/web-components/src/components/style-picker/__tests__/style-picker.test.js
- packages/web-components/src/components/style-picker/components/style-picker-option/src/style-picker-option.template.ts
- packages/web-components/src/components/style-picker/package.json
- yarn.lock
Closes https://github.com/carbon-design-system/ibm-products/issues/8251
updates icons in the `style-picker` web component from `@carbon/web-components` to `@carbon/icons`
> fix: stylepicker replace icons

- packages/web-components/src/components/style-picker/__stories__/_placeholders.ts
Fixes an import issue in `style-picker` that was causing the react netlify deploy to fail in @asfordmatt's global header PR.
**Changed**
- `packages/web-components/src/components/style-picker/__stories__/_placeholders.ts`
Both web component and react deploys build from netlify
> fix(style-picker): update types import

- packages/web-components/package.json
- packages/web-components/src/components/global-header/package.json
- packages/web-components/src/components/global-header/web-test-runner.config.mjs
- yarn.lock
Our unit tests use a different setup, so run them separately to the others
> chore(wc-global-header): run unit tests for global-header separately
